TRUNCATE TABLE IDN_OAUTH2_AUTHZ_CODE_SCOPE RESTART IDENTITY CASCADE;
TRUNCATE TABLE FLOW_USER_DATA RESTART IDENTITY CASCADE;
TRUNCATE TABLE IDN_OAUTH2_AUTHZ_CODE RESTART IDENTITY CASCADE;
TRUNCATE TABLE FLOW_CONTEXT RESTART IDENTITY CASCADE;
