create database SESSION_DB;

use SESSION_DB;

CREATE TABLE IF NOT EXISTS IDN_AUTH_SESSION_STORE (
    SESSION_ID VARCHAR (100) NOT NULL,
    SESSION_TYPE VARCHAR(100) NOT NULL,
    OPERATION VARCHAR(10) NOT NULL,
    SESSION_OBJECT BLOB,
    TIME_CREATED BIGINT,
    TENANT_ID INTEGER DEFAULT -1,
    EXPIRY_TIME BIGINT,
    PRIMARY KEY (SESSION_ID, SESSION_TYPE, TIME_CREATED, OPERATION)
)DEFAULT CHARACTER SET latin1 ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_AUTH_TEMP_SESSION_STORE (
    SESSION_ID VARCHAR (100) NOT NULL,
    SESSION_TYPE VARCHAR(100) NOT NULL,
    OPERATION VARCHAR(10) NOT NULL,
    SESSION_OBJECT BLOB,
    TIME_CREATED BIGINT,
    TENANT_ID INTEGER DEFAULT -1,
    EXPIRY_TIME BIGINT,
    PRIMARY KEY (SESSION_ID, SESSION_TYPE, TIME_CREATED, OPERATION)
)DEFAULT CHARACTER SET latin1 ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_AUTH_USER_SESSION_MAPPING (
    ID INTEGER NOT NULL AUTO_INCREMENT,
    USER_ID VARCHAR(255) NOT NULL,
    SESSION_ID VARCHAR(255) NOT NULL,
    CONSTRAINT USER_SESSION_STORE_CONSTRAINT UNIQUE (USER_ID, SESSION_ID),
    PRIMARY KEY (ID))DEFAULT CHARACTER SET latin1;

CREATE TABLE IF NOT EXISTS IDN_AUTH_SESSION_APP_INFO (
    SESSION_ID VARCHAR (100) NOT NULL,
    SUBJECT VARCHAR (100) NOT NULL,
    APP_ID INTEGER NOT NULL,
    INBOUND_AUTH_TYPE VARCHAR (255) NOT NULL,
    PRIMARY KEY (SESSION_ID, SUBJECT, APP_ID, INBOUND_AUTH_TYPE)
)DEFAULT CHARACTER SET latin1 ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_AUTH_SESSION_META_DATA (
    SESSION_ID VARCHAR (100) NOT NULL,
    PROPERTY_TYPE VARCHAR (100) NOT NULL,
    VALUE VARCHAR (255) NOT NULL,
    PRIMARY KEY (SESSION_ID, PROPERTY_TYPE, VALUE)
)DEFAULT CHARACTER SET latin1 ENGINE INNODB;

CREATE TABLE IF NOT EXISTS IDN_AUTH_USER (
    USER_ID VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    TENANT_ID INTEGER NOT NULL,
    DOMAIN_NAME VARCHAR(255) NOT NULL,
    IDP_ID INTEGER NOT NULL,
    PRIMARY KEY (USER_ID),
    CONSTRAINT USER_STORE_CONSTRAINT UNIQUE (USER_NAME, TENANT_ID, DOMAIN_NAME, IDP_ID)
)DEFAULT CHARACTER SET latin1;

CREATE TABLE IF NOT EXISTS IDN_AUTH_WAIT_STATUS (
    ID              INTEGER AUTO_INCREMENT NOT NULL,
    TENANT_ID       INTEGER                NOT NULL,
    LONG_WAIT_KEY   VARCHAR(255)           NOT NULL,
    WAIT_STATUS     CHAR(1) NOT NULL DEFAULT '1',
    TIME_CREATED    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRE_TIME     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    CONSTRAINT IDN_AUTH_WAIT_STATUS_KEY UNIQUE (LONG_WAIT_KEY)
)DEFAULT CHARACTER SET latin1 ;

-- IDN_AUTH_SESSION_STORE --
CREATE INDEX IDX_IDN_AUTH_SESSION_TIME ON IDN_AUTH_SESSION_STORE (TIME_CREATED);
CREATE INDEX IDX_IDN_AUTH_SSTR_ST_OP_ID_TM ON IDN_AUTH_SESSION_STORE (OPERATION, SESSION_TYPE, SESSION_ID, TIME_CREATED);
CREATE INDEX IDX_IDN_AUTH_SSTR_ET_ID ON IDN_AUTH_SESSION_STORE (EXPIRY_TIME, SESSION_ID);

-- IDN_AUTH_TEMP_SESSION_STORE --
CREATE INDEX IDX_IDN_AUTH_TMP_SESSION_TIME ON IDN_AUTH_TEMP_SESSION_STORE (TIME_CREATED);

-- IDN_AUTH_USER --
CREATE INDEX IDX_AUTH_USER_UN_TID_DN ON IDN_AUTH_USER (USER_NAME, TENANT_ID, DOMAIN_NAME);
CREATE INDEX IDX_AUTH_USER_DN_TOD ON IDN_AUTH_USER (DOMAIN_NAME, TENANT_ID);

-- IDN_AUTH_USER_SESSION_MAPPING --
CREATE INDEX IDX_USER_ID ON IDN_AUTH_USER_SESSION_MAPPING (USER_ID);
CREATE INDEX IDX_SESSION_ID ON IDN_AUTH_USER_SESSION_MAPPING (SESSION_ID);

-- IDN_AUTH_SESSION_APP_INFO --
CREATE INDEX IDX_AUTH_SAI_UN_AID_SID ON IDN_AUTH_SESSION_APP_INFO (APP_ID, SUBJECT, SESSION_ID);

-- add tables that could vary in different IS packs
CREATE TABLE IF NOT EXISTS IDN_AUTH_TEMP_SESSION_STORE(id int);
