CREATE TABLE IDN_OAUTH2_ACCESS_TOKEN_BAK AS SELECT * FROM IDN_OAUTH2_ACCESS_TOKEN;
CREATE TABLE IDN_OAUTH2_ACCESS_TOKEN_SCOPE_BAK AS SELECT * FROM IDN_OAUTH2_ACCESS_TOKEN_SCOPE;
CREATE TABLE IDN_OAUTH2_TOKEN_BINDING_BAK AS SELECT * FROM IDN_OAUTH2_TOKEN_BINDING;
