SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE IDN_OAUTH2_TOKEN_BINDING;
TRUNCATE TABLE IDN_OAUTH2_ACCESS_TOKEN_SCOPE;
TRUNCATE TABLE IDN_OAUTH2_ACCESS_TOKEN;

INSERT INTO IDN_OAUTH2_ACCESS_TOKEN SELECT * FROM IDN_OAUTH2_ACCESS_TOKEN_BAK;
INSERT INTO IDN_OAUTH2_ACCESS_TOKEN_SCOPE SELECT * FROM IDN_OAUTH2_ACCESS_TOKEN_SCOPE_BAK;
INSERT INTO IDN_OAUTH2_TOKEN_BINDING SELECT * FROM IDN_OAUTH2_TOKEN_BINDING_BAK;

SET FOREIGN_KEY_CHECKS = 1;
