-- add tables that need to be truncated
TRUNCATE TABLE IDN_AUTH_SESSION_STORE CASCADE;
TRUNCATE TABLE IDN_AUTH_TEMP_SESSION_STORE CASCADE;
TRUNCATE TABLE IDN_OAUTH2_AUTHORIZATION_CODE CASCADE;
TRUNCATE TABLE IDN_OAUTH2_AUTHZ_CODE_SCOPE CASCADE;
TRUNCATE TABLE IDN_OAUTH2_TOKEN_BINDING CASCADE;
TRUNCATE TABLE IDN_OAUTH2_ACCESS_TOKEN_SCOPE CASCADE;
TRUNCATE TABLE IDN_OAUTH2_ACCESS_TOKEN CASCADE;
TRUNCATE TABLE IDN_AUTH_SESSION_META_DATA CASCADE;
TRUNCATE TABLE IDN_AUTH_SESSION_APP_INFO CASCADE;
TRUNCATE TABLE IDN_AUTH_USER_SESSION_MAPPING CASCADE;
