-- Before using this script make sure to add the stored procedure truncate_non_empty_table.sql to the database
truncate_non_empty_table IDN_AUTH_SESSION_STORE;
GO
truncate_non_empty_table IDN_AUTH_TEMP_SESSION_STORE;
GO
truncate_non_empty_table IDN_OAUTH2_AUTHORIZATION_CODE;
GO
truncate_non_empty_table IDN_OAUTH2_ACCESS_TOKEN_SCOPE;
GO
truncate_non_empty_table IDN_OAUTH2_ACCESS_TOKEN;
GO
truncate_non_empty_table IDN_AUTH_SESSION_META_DATA;
GO
truncate_non_empty_table IDN_AUTH_SESSION_APP_INFO;
GO
truncate_non_empty_table IDN_AUTH_USER_SESSION_MAPPING;
GO
truncate_non_empty_table IDN_OAUTH2_AUTHZ_CODE_SCOPE;
GO
truncate_non_empty_table IDN_OAUTH2_TOKEN_BINDING;
GO
